<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
																															 
<!--
   Copyright (c) 2006, Paul Kenney
   All rights reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Writing Tests</title>

	<style type="text/css">
		@import url(assets/styles.css);
	</style>
</head>

<body>

<h2>Writing Tests</h2>

<p>
	So, how does one go about writing tests? First, you need something to test. 
	To keep this simple, let's imagine we have a component called "Calculator". 
	It has the following methods, each of which returns a numeric value:
</p>


<code class="cfml">
&lt;cfcomponent name=&quot;Calculator&quot; output=&quot;false&quot; 
      hint=&quot;This is a basic calculator&quot;&gt;

   &lt;cffunction name=&quot;add&quot; returntype=&quot;numeric&quot; access=&quot;public&quot; output=&quot;false&quot;
         hint=&quot;Adds op2 to op1.&quot;&gt;
      &lt;cfargument name=&quot;op1&quot; type=&quot;numeric&quot; required=&quot;true&quot; hint=&quot;Left operand.&quot;/&gt;
      &lt;cfargument name=&quot;op2&quot; type=&quot;numeric&quot; required=&quot;true&quot; hint=&quot;Right operand&quot;/&gt;
	  
      &lt;cfreturn (arguments.op1 + arguments.op2)/&gt;
   &lt;/cffunction&gt;

   
   &lt;cffunction name=&quot;subtract&quot; returntype=&quot;numeric&quot; access=&quot;public&quot; output=&quot;false&quot; 
         hint=&quot;Subtracts op2 from op1.&quot;&gt;
      &lt;cfargument name=&quot;op1&quot; type=&quot;numeric&quot; required=&quot;true&quot; hint=&quot;Left operand.&quot;/&gt;
      &lt;cfargument name=&quot;op2&quot; type=&quot;numeric&quot; required=&quot;true&quot; hint=&quot;Right operand.&quot;/&gt;
	  
      &lt;cfreturn (arguments.op1 - arguments.op2)/&gt;
   &lt;/cffunction&gt;


   &lt;cffunction name=&quot;multiply&quot; returntype=&quot;numeric&quot; access=&quot;public&quot; output=&quot;false&quot; 
         hint=&quot;Multiplies op1 by op2.&quot;&gt;
      &lt;cfargument name=&quot;op1&quot; type=&quot;numeric&quot; required=&quot;true&quot; hint=&quot;Left operand.&quot;/&gt;
      &lt;cfargument name=&quot;op2&quot; type=&quot;numeric&quot; required=&quot;true&quot; hint=&quot;Right operand.&quot;/&gt;
	  
      &lt;cfreturn (arguments.op1 * arguments.op2)/&gt;
   &lt;/cffunction&gt;


   &lt;cffunction name=&quot;divide&quot; returntype=&quot;numeric&quot; access=&quot;public&quot; output=&quot;false&quot; 
         hint=&quot;Divides numerator by divisor.&quot;&gt;
      &lt;cfargument name=&quot;numerator&quot; type=&quot;numeric&quot; required=&quot;true&quot; hint=&quot;&quot;/&gt;
      &lt;cfargument name=&quot;divisor&quot; type=&quot;numeric&quot; required=&quot;true&quot; hint=&quot;&quot;/&gt;
	  
      &lt;cfreturn (arguments.numerator / arguments.divisor)/&gt;
   &lt;/cffunction&gt;

&lt;/cfcomponent&gt;</code>

<p>
	We need to test that this component does everything its says it does without any
	errors.  To do this we can write a Test Case.  A Test Case is a component that 
	defines and runs one or more tests. Since this Test Case is going to test the 
	Calculator component, let's call it "CalculatorTest".
</p>

<h3>What's In a Test?</h3>

<p>
	What needs to be tested in Calculator?  We should at least test that the four
	methods (add, subtract, multiply and divide) work.  Create one test for each
	one and call them <var>testAdd()</var>, <var>testSubtract()</var>, 
	<var>testMultiply</var> and <var>testDivide()</var>. Now, let's create 
	the CalculatorTest component. In order for CalculatorTest to be considered a 
	Test Case by the testing framework and have access to the functionality of the 
	framework, this component needs to extend the <var>org.cfcunit.framework.TestCase</var> 
	component.  For each test create a method with the name of the test&mdash;always make sure 
	that a test method name is prefixed with "test"&mdash;with a returntype of "void" and 
	"public" access. This ensures that the testing framework recognizes these four methods 
	as your individual tests.
</p>

<p>So far, this is what "CalculatorTest" looks like:</p>

<code class="cfml">&lt;cfcomponent name=&quot;CalculatorTest&quot; extends=&quot;org.cfcunit.framework.TestCase&quot; 
   output=&quot;false&quot; 
   hint=&quot;This tests the Calculator component.&quot;&gt;

   &lt;cffunction name=&quot;testAdd&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;/cffunction&gt;

   &lt;cffunction name=&quot;testSubtract&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;/cffunction&gt;

   &lt;cffunction name=&quot;testMultiply&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;/cffunction&gt;

   &lt;cffunction name=&quot;testDivide&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;/cffunction&gt;
   
&lt;/cfcomponent&gt;</code>

<p>
	While this isn't much to look at, this is will run as 4 valid tests.  To see this, just open up the test runner,
	enter the fully qualified name of this component, and press "Run Test".  You should get the message 
	"Test Results: All Passed!":
</p>

<p align="center"><img src="assets/images/results_v1.gif" alt="All Tests Passed" width="528" height="185" /></p>

<p>
	Now lets go ahead and write the test for the <var>add()</var> method.  In "CalculatorTest", this is the 
	<var>testAdd()</var> method. The <var>add()</var> method is pretty simple.  It takes two numeric parameters and 
	returns their sum.  To test this, we simply create an instance of Calculator and call its add() method 
	with two known values that produce a known sum.  A simple case is "1 + 1 = 2".  We then take the result 
	of the calculation and compare it to the expected value of 2.  This is done using an assertion 
	method&mdash;in this case we use <var>assertEqualsNumber()</var>&mdash;which takes the expected value and 
	the actual value and compares them.  If they are not equal, it signals a test failure and provides a message 
	that indicates the nature of the failure.
</p>

<p>Here is the code for <var>testAdd()</var>:</p>

<code class="cfml">&lt;cffunction name=&quot;testAdd&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;cfset var calc = CreateObject(&quot;component&quot;, &quot;Calculator&quot;)&gt;
   
   &lt;cfset assertEqualsNumber(2, calc.add(1, 1))&gt;
&lt;/cffunction&gt;</code>

<p>
	Add this code and run the test runner.  The test passes.  Let's go ahead and add the tests for
	<var>subtract()</var>, <var>multiply()</var> and <var>divide()</var>:
</p>

<code class="cfml">&lt;cffunction name=&quot;testSubtract&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;cfset var calc = CreateObject(&quot;component&quot;, &quot;Calculator&quot;)&gt;
	
   &lt;cfset assertEqualsNumber(1, calc.subtract(3, 2))&gt;
   &lt;cfset assertEqualsNumber(0, calc.subtract(1, 1))&gt;
   &lt;cfset assertEqualsNumber(-2, calc.subtract(-1, 1))&gt;
   &lt;cfset assertEqualsNumber(-2, calc.subtract(1, -1))&gt;
&lt;/cffunction&gt;
	

&lt;cffunction name=&quot;testMultiply&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;cfset var calc = CreateObject(&quot;component&quot;, &quot;Calculator&quot;)&gt;
	
   &lt;cfset assertEqualsNumber(10, calc.multiply(5, 2))&gt;
   &lt;cfset assertEqualsNumber(0, calc.multiply(5, 0))&gt;
   &lt;cfset assertEqualsNumber(-10, calc.multiply(-5, 2))&gt;
&lt;/cffunction&gt;
	

&lt;cffunction name=&quot;testDivide&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;cfset var calc = CreateObject(&quot;component&quot;, &quot;Calculator&quot;)&gt;
	
   &lt;cfset assertEqualsNumber(3, calc.divide(15, 5))&gt;
   &lt;cfset assertEqualsNumber(-3, calc.divide(15, -5))&gt;
   &lt;cfset assertEqualsNumber(0, calc.divide(0, 1))&gt;
&lt;/cffunction&gt;</code>
	
<p>Run the tests again, and there is a different result:</p>
<p align="center"><img src="assets/images/results_v2.gif" alt="Test failure" width="512" height="218" /></p>

<p>
	Well, it seems that there is a problem with one of the tests. Taking a look at the <var>testSubtract()</var> test method, 
	the highlighed line below reveales failure's source:
</p>

<code class="cfml">&lt;cffunction name=&quot;testSubtract&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;cfset var calc = CreateObject(&quot;component&quot;, &quot;Calculator&quot;)&gt;
	
   &lt;cfset assertEqualsNumber(1, calc.subtract(3, 2))&gt;
   &lt;cfset assertEqualsNumber(0, calc.subtract(1, 1))&gt;
   &lt;cfset assertEqualsNumber(-2, calc.subtract(-1, 1))&gt;
<span class="highlight">   &lt;cfset assertEqualsNumber(-2, calc.subtract(1, -1))&gt;</span>&lt;/cffunction&gt;
</code>

<p>
	The problem is the arguments specified in the <var>assertEqualsNumber()</var> method call which checks that 
	-2 is the result of <var>calc.subtract(1, -1)</var>. Of course, 1 - (1) equals 0, so this assertion fails and displays an 
	assertion failure message in the test results.  To remove the failure in test, simply change the first "expected"
	argument in <var>assertEqualsNumber()</var> to 2:
</p>

<code class="cfml">&lt;cffunction name=&quot;testSubtract&quot; returntype=&quot;void&quot; access=&quot;public&quot; output=&quot;false&quot;&gt;
   &lt;cfset var calc = CreateObject(&quot;component&quot;, &quot;Calculator&quot;)&gt;
	
   &lt;cfset assertEqualsNumber(1, calc.subtract(3, 2))&gt;
   &lt;cfset assertEqualsNumber(0, calc.subtract(1, 1))&gt;
   &lt;cfset assertEqualsNumber(-2, calc.subtract(-1, 1))&gt;
<span class="highlight">   &lt;cfset assertEqualsNumber(2, calc.subtract(1, -1))&gt;</span>&lt;/cffunction&gt;
</code>


<h3>Test Fixtures - Bringing Common Test Code Together</h3>

<p>
	When examining each of the test methods you might notice that each of them has code in common.  It is the
	first line that instantiates the <var>Calculator</var> object. This is a very common occurance when
	creating unit tests, and is commonly refered to the <strong>test fixture</strong>.  The solution to this duplicate code is
	to consolidate it into a separate method called <var>setUp()</var> which must have a "void" return type and
	access of "private".  The testing framework is responsible for calling this specific method before each test
	method.  Here is what the CalculatorTest component looks like when utilizing the <var>setUp()</var> method:
</p>

<code class="cfml">&lt;cfcomponent name=&quot;CalculatorTest&quot; extends=&quot;org.cfcunit.framework.TestCase&quot; 
   output=&quot;false&quot; 
   hint=&quot;This tests the Calculator component.&quot;&gt;

<span class="highlight">   &lt;cfset variables.calculator = &quot;&quot;&gt;

   &lt;cffunction name=&quot;setUp&quot; returntype=&quot;void&quot; access=&quot;private&quot;&gt;
      &lt;cfset variables.calculator = CreateObject(&quot;component&quot;, &quot;Calculator&quot;)&gt;
   &lt;/cffunction&gt;</span>


   &lt;cffunction name=&quot;testAdd&quot; returntype=&quot;void&quot; access=&quot;public&quot;&gt;
      &lt;cfset assertEqualsNumber(2, variables.calculator.add(1, 1))&gt;
   &lt;/cffunction&gt;


   &lt;cffunction name=&quot;testSubtract&quot; returntype=&quot;void&quot; access=&quot;public&quot;&gt;
      &lt;cfset assertEqualsNumber(1, variables.calculator.subtract(3, 2))&gt;
      &lt;cfset assertEqualsNumber(0, variables.calculator.subtract(1, 1))&gt;
      &lt;cfset assertEqualsNumber(-2, variables.calculator.subtract(-1, 1))&gt;
      &lt;cfset assertEqualsNumber(2, variables.calculator.subtract(1, -1))&gt;
   &lt;/cffunction&gt;
	

   &lt;cffunction name=&quot;testMultiply&quot; returntype=&quot;void&quot; access=&quot;public&quot;&gt;
      &lt;cfset assertEqualsNumber(10, variables.calculator.multiply(5, 2))&gt;
      &lt;cfset assertEqualsNumber(0, variables.calculator.multiply(5, 0))&gt;
      &lt;cfset assertEqualsNumber(-10, variables.calculator.multiply(-5, 2))&gt;
   &lt;/cffunction&gt;
	

   &lt;cffunction name=&quot;testDivide&quot; returntype=&quot;void&quot; access=&quot;public&quot;&gt;
      &lt;cfset assertEqualsNumber(3, variables.calculator.divide(15, 5))&gt;
      &lt;cfset assertEqualsNumber(-3, variables.calculator.divide(15, -5))&gt;
      &lt;cfset assertEqualsNumber(0, variables.calculator.divide(0, 1))&gt;
   &lt;/cffunction&gt;
   
&lt;/cfcomponent&gt;</code>

<p>
	In addition to the <var>setUp()</var> method, there is also a method called <var>tearDown()</var> that
	is called immediately after each of the tests run by the framework.  It is used to restore the state
	of the system to where it was before the test was run.  Many times this sort of thing includes cleaning up
	files, resetting variables and undoing any changes in a database.  These two methods allow you to write
	tests without having to worry about the details of how things get set up every time.  You are also more free
	to make changes to the test fixture since it resides in only one place instead of four.
</p>


<h3>Errors and Failures</h3>

<p>
	The four tests written so far test only the most basic functionality of the Calculator component.  What we really want
	to test, though, are the boundary cases--things like dividing by zero and floating point calculations. That said, let's
	write a test that shows what happens when attempting to divide a number by zero.
</p>

<code class="cfml">&lt;cffunction name=&quot;testDivideByZero&quot; returntype=&quot;void&quot; access=&quot;public&quot;&gt;
   &lt;cfset var value = variables.calculator.divide(10, 0))&gt;
&lt;/cffunction&gt;</code>

<p>
	Running the tests again, we get the following results:
</p>

<p align="center"><img src="assets/images/results_v5.gif" alt="Test Failed" /></p>

<p>
	Notice that the status for the <var>testDivideByZero</var> test is "Error".  If you look back at the results for the
	last time we had a problem with the tests you will notice that the status for the <var>testSubtraction</var> test
	was "Failure".  What's the difference?  Basically, a Failure is the result of an unsatisfied assertion as specified in
	one of the <var>assert*()</var> methods.  An Error on the other hand is any unexpected (thus unchecked) exception 
	that is thrown by the component under test.  It usually indicates something that you do not test, but may wish to
	in future tests.
</p>

<p>
	Since errors are not expected and thus not tested for, a bit of information is provided with the error notification.
	Aside from the name of the TestCase, the exception's message and detail values are displayed.  The exception
	type is also provied in two forms: first is the Java-level exception type, followed by the more general 
	ColdFusion-level exception type.  The last item is the stacktrace at the time of the exception.  All this information
	is extremely helpful in tracking down errors:
</p>

<p align="center"><img src="assets/images/error_v5.gif" /></p>

<p>
	To fix this error in the test, we have several options.  First, the Calculator component could be modified so
	that is does not throw "DivideByZeroException". This would allow the test to pass, but what would the
	<var>divide()</var> method return instead of throwing an exception?  There really isn't a good answer to that
	question since the value is really undefined.  The second option is to keep the exception as it is, but change
	the test to anticipate the exception and catch it.  In fact, the test should fail if the exception is NOT
	thrown.  Here is the new code for the <var>testDivideByZero()</var> method:
</p>

<code class="cfml">&lt;cffunction name=&quot;testDivideByZero&quot; returntype=&quot;void&quot; access=&quot;public&quot;&gt;
   &lt;cfset var value = &quot;&quot;&gt;
   
   &lt;cftry&gt;
      &lt;cfset value = variables.calculator.divide(10, 0)&gt;
      &lt;cfset fail(&quot;DivideByZeroException was not thrown.&quot;)&gt;

      &lt;cfcatch type=&quot;coldfusion.runtime.DivideByZeroException&quot;&gt;
      &lt;/cfcatch&gt;
   &lt;/cftry&gt;
&lt;/cffunction&gt;</code>

<p>
	If the tests are run again, there should be no errors and no failures.
</p>

</body>

</html>